import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button, ConfigProvider, Space } from 'antd';
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
    >
      <body className={inter.className}>
        <div>
          <Link href={"/"}>
            <h1 className="text-center font-bold text-6xl">
              Home
            </h1>
          </Link>
        </div>
        <div className="flex flex-row">
          <div className="m-2 basis-1/4">
            <Button className="w-full" type="default" href="/page1">Page 1</Button>
          </div>
          <div className="m-2 basis-1/4">
            <Button className="w-full" type="default" href="/page2">Page 2</Button>
          </div>
          <div className="m-2 basis-1/4">
            <Button className="w-full" type="default" href="/page3">Page 3</Button>
          </div>
          <div className="m-2 basis-1/4">
            <Button className="w-full" type="default" href="/page4">Page 4</Button>
          </div>
        </div>
        {children}
      </body>
    </ConfigProvider>
    </html>
  );
}
